### PR TITLE
integrate blocks of yaml in tutorial pages

### PR DESCRIPTION
**Pull request by bernard357**
since demo files have gone to plumbery-contrib

This is important for pages publshed at readthedocs

### CODE REVIEW

**Comment by tonybaloney** [comment]
@bernard357 the tutorial pages are also going to move to plumbery-contrib so this PR probably isn't needed. I'll try and give you a run down tonight

**Comment by bernard357** [comment]
Beware that for the time being the readthedocs site is broken, and no tutorial is displayed. Would it make sense to just accept the PR right now, and then to review the best options for the evolution of the readthedocs resource? Currently the experience of people coming to the readthedocs is broken, that's why

**Comment by bernard357** [comment]
Thanks Anthony. I will demo plumbery later today, and having readthedocs available will help. :-)

**Comment by tonybaloney** [comment]
Make sure you show the new doc site too! 

Sent from Outlook Mobile




On Tue, Mar 15, 2016 at 2:21 AM -0700, "Bernard Paques" <notifications@github.com> wrote:












Thanks Anthony. I will demo plumbery later today, and having readthedocs available will help. :-)

**Pull request merged**
